version: '3'
services:
  server:
    image: gocd/gocd-server:v17.3.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./gocd-server/godata:/godata
      - ./gocd-server/home:/home/go

  agent:
    image: hpcsc/gocd-agent-dotnet:gocd-17.4.0-ubuntu-16.04-net-1.1
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
    volumes:
      - ./gocd-agent/godata:/godata
      - ./gocd-agent/home:/home/go
