version: '3'
services:
  server:
    image: gocd/gocd-server:v17.3.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./server/godata:/godata
      - ./server/home:/home/go

  agent-1:
    image: gocd/gocd-agent-ubuntu-16.04:v17.4.0
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
    volumes:
      - ./agents/agent-1/godata:/godata
      - ./agents/agent-1/home:/home/go

  agent-2:
    image: gocd/gocd-agent-ubuntu-16.04:v17.4.0
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
    volumes:
      - ./agents/agent-2/godata:/godata
      - ./agents/agent-2/home:/home/go

  agent-3:
    image: hpcsc/gocd-agent-dotnet:gocd-17.4.0-ubuntu-16.04-net-1.1
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
    volumes:
      - ./agents/agent-3/godata:/godata
      - ./agents/agent-3/home:/home/go
      - /var/run/docker.sock:/var/run/docker.sock
