version: '3'
services:
  server:
    image: gocd/gocd-server:${GOCD_VERSION}
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./server/godata:/godata
      - ./server/home:/home/go

  agent-1:
    image: gocd/gocd-agent-docker-dind:${GOCD_VERSION}
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
    privileged: true
    volumes:
      - ./agents/agent-1/godata:/godata
      - ./agents/agent-1/home:/home/go

  agent-2:
    image: gocd/gocd-agent-docker-dind:${GOCD_VERSION}
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
    privileged: true
    volumes:
      - ./agents/agent-2/godata:/godata
      - ./agents/agent-2/home:/home/go

  agent-3:
    image: gocd/gocd-agent-docker-dind:${GOCD_VERSION}
    depends_on:
      - server
    environment:
      GO_SERVER_URL: https://server:8154/go
    privileged: true
    volumes:
      - ./agents/agent-3/godata:/godata
      - ./agents/agent-3/home:/home/go
